Refactor Lambda
StackVista/stackstate-agent-integrations pull request #168
Opened 2021-06-11 08:42 UTC by Eelviny

### Step 1: Link to Jira issue
https://stackstate.atlassian.net/browse/STAC-13265

### Step 2: Description of changes
- Refactor lambda code
- Add IAM permissions checks
- Attempt to return a minimal component if get_function fails
- Add Schematics validation

### Step 3: Did you add / update tests for your changes in the right area?
- [x] Unit/Component test
- [ ] Integration test	

### Step 4: I'm confident that everything is properly tested:
I got a PO / QA Approval by:
- [ ] Name

### Step 5: Can we ship this feature to production?
- [ ] Yes, I'm proud of my work. Ship it! :ship:

2021-06-11 09:33 UTC, Jacco requested changes

2021-06-11 09:33 UTC, Jacco commented on aws_topology/stackstate_checks/aws_topology/resources/lambdaf.py
> +    State = StringType(default="Enabled")
default "UNKNOWN" would be better

2021-06-14 12:17 UTC, zandrewitte approved these changes

2021-06-14 14:59 UTC, Jacco approved these changes

2021-06-14 15:19 UTC, merged