Send aws_topology snapshot before raising errors
StackVista/stackstate-agent-integrations pull request #173
Opened 2021-06-14 13:39 UTC by Eelviny

### Step 1: Link to Jira issue
https://stackstate.atlassian.net/browse/STAC-13287

### Step 2: Description of changes
Ensure that `stop_snapshot` is called before raising all found errors, to ensure that one failing API does not block the sending of successful APIs.

### Step 3: Did you add / update tests for your changes in the right area?
- [x] Unit/Component test
- [ ] Integration test	

### Step 4: I'm confident that everything is properly tested:
I got a PO / QA Approval by:
- [ ] Name

### Step 5: Can we ship this feature to production?
- [ ] Yes, I'm proud of my work. Ship it! :ship:

2021-06-14 14:53 UTC, Jacco requested changes

2021-06-14 14:53 UTC, Jacco commented on aws_topology/stackstate_checks/aws_topology/aws_topology.py
> +        self.delete_ids += agent_proxy.delete_ids
Move this to under components_seen :-)

2021-06-15 10:30 UTC, Eelviny commented
Continuing from the discussion in Slack -  @zandrewitte you had a concern that we're attempting to close a snapshot even if there are errors.

Yes, we are attempting to close if there are errors, but only the errors that we specifically catch (like the accessdenied errors). Any uncaught errors will make the snapshot collection completely fail as normal.

2021-06-15 11:59 UTC, Jacco commented
Above statement is not how it is intended

2021-06-15 13:08 UTC, Eelviny commented
This actually doesn't fix the underlying issue, closing

2021-06-15 13:08 UTC, closed without merging