add persistent state for integrations
StackVista/stackstate-agent-integrations pull request #78
Opened 2020-11-10 09:10 UTC by zandrewitte

### Step 1: Link to Jira issue

### Step 2: Description of changes

### Step 3: Did you add / update tests for your changes in the right area?
- [ ] Unit/Component test
- [ ] Integration test	

### Step 4: I'm confident that everything is properly tested:
I got a PO / QA Approval by:
- [ ] Name

### Step 5: Can we ship this feature to production?
- [ ] Yes, I'm proud of my work. Ship it! :ship:

2020-11-10 16:04 UTC, hruhek commented on stackstate_checks_base/stackstate_checks/base/utils/persistent_state.py
> +from schematics.models import Model
this line should look like this `from schematics import Model` as `Model` is imported in `schematics.__init__py`

2020-11-13 10:07 UTC, TizianoPerrucci requested changes
We also talked about the possibility to have a `AgentStatefullCheck` class that can be extended by check that need state. It can provide awareness into the base class that the check uses state and can do proper check and state creation before the `check.run`.
Right now the base class does not have any clue if the check wanna use state and we defer the state write till the end after the `check.run` so we will know if there are any problems in writing files only at the end.

2020-11-13 10:07 UTC, TizianoPerrucci commented on stackstate_checks_dev/stackstate_checks/dev/plugin/plugin.py
> +            self.persistent_state.clear(instance)
split this part so we can reuse it

2020-11-13 10:07 UTC, TizianoPerrucci commented on stackstate_checks_base/tests/test_utils.py
> +        assert state.persistent_state.get_state(instance, TestStorageSchema) is None
reuse the fixture here

2020-11-20 09:19 UTC, TizianoPerrucci requested changes

2020-11-20 09:19 UTC, TizianoPerrucci commented on stackstate_checks_base/stackstate_checks/base/utils/persistent_state.py
> +            if not os.path.exists(os.path.dirname(instance.file_location)):
combine in one `try` with the `write` below

2020-11-20 09:19 UTC, TizianoPerrucci commented on stackstate_checks_dev/stackstate_checks/dev/plugin/plugin.py
> +        def assert_state_check(self, check, pre_run_state, post_run_state, state_schema=None):
rename 
`expected_pre_run_state`
`expected_post_run_state`

2020-11-20 09:19 UTC, TizianoPerrucci commented on stackstate_checks_base/stackstate_checks/base/checks/base.py
> +        return "{}/{}.d".format(self.get_agent_conf_d_path(), self.name)
what about windows ?

2020-11-20 09:19 UTC, TizianoPerrucci commented on stackstate_checks_base/stackstate_checks/base/utils/persistent_state.py
> +    def __init__(self, instance_key, check_conf_d_path):
do not allow `None` or empty string

2020-11-20 16:35 UTC, TizianoPerrucci approved these changes

2020-11-21 10:51 UTC, merged